### ISSUE TITLE
Example project repos

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#14]
At the [Basel hackathon](https://helix-home-adobe.project-helix.page/hackathons/5-bsl.html?) we discussed creating example project repos which get users started quickly and let them progressively discover more Helix (Pages) features:

- [ ] First Example (e.g. https://github.com/bdelacretaz/helix-example-zero)
  - content only: index.md (or use README.md as fallback?)
  - custom header and footer: add header.md & footer.md
  - add html files
  - custom styling: add style.css as override
- [ ] Advanced Example
  - custom code: add src folder with html.htl & html.pre.js
  - separate code and content: add helix-config.yaml
  - proxy strain

**Comment by bdelacretaz** [comment]
https://github.com/bdelacretaz/helix-example-zero is a first step towards this.

We'll also need to define GitHub topics that uniquely identify these example repos, for now I have used [helix-example](https://github.com/topics/helix-example)

**Comment by bdelacretaz** [comment]
As mentioned on chat, my current idea is to refine the structure of https://github.com/bdelacretaz/helix-example-zero and review that before creating more examples. Created https://github.com/adobe/helix-home/issues/27 for that.

**Comment by bdelacretaz** [comment]
See also https://github.com/adobe/helix-home/pull/26 which has a discussion on a single vs multiple example repos.

**Comment by tripodsan** [comment]
>See also https://github.com/adobe/helix-home/pull/26 which has a discussion on a single vs multiple example repos.

@bdelacretaz i think initially we should gather the examples in one repo. Once we have the 3-4 initial ones, we can divide them up in individual repos. This initial phase will last about 2 weeks.

**Comment by bdelacretaz** [comment]
> i think initially we should gather the examples in one repo

Would you agree to two repos? One for "pure content" examples, no programming, and another with the examples that require programming, pre.js etc.

**Comment by rofe** [comment]
I can agree to many things :)

Would the "pure content" one include header, footer, CSS and HTML files (steps 1 - 4 in https://github.com/adobe/helix-home/pull/26), whereas the advanced one would cover steps 5 and beyond?

**Comment by bdelacretaz** [comment]
Yes that's the idea, coming back to the 3 personas discussed at https://github.com/adobe/helix-home/issues/31:

* The "pure content" example is meant for people who know GitHub, Markdown, HTML, CSS
* The "programming" example is meant for people who in addition to that are comfortable with Node.js programming

And for those who have none of these skills, a narrative guides them through the examples.

I'm not sure how we'll do progressive disclosure in those repos but we can start by fully fleshing them out and later looking at how to deliver the information in stages if it makes sense.

**Comment by rofe** [comment]
Makes sense. I regrouped the features in the main issue description into examples 1 and 2 accordingly.

I removed "custom domain" for now, unless this is something we will be able to demonstrate in an example repo...

**Comment by rofe** [comment]
Instead of numbers, how about using "first example" and "advanced example"? We could even add a "proficiency" later ;)

**Comment by bdelacretaz** [comment]
I have made a different proposal at https://github.com/adobe/helix-home/issues/31 for the names and content of the example repos. I suggest that we move the general discussion about examples there, as the examples cover more than just this module.

**Comment by bdelacretaz** [comment]
As discussed at https://github.com/adobe/helix-home/issues/31 I have now created the https://github.com/adobe/helix-example-basic repository for the "content only" example (which we can expand - it's a starting point).

I have "hidden" the test code which validates the https://helix-example-basic-adobe.project-helix.page/ in the `test-code` branch to keep the master branch focused on Helix Pages content: I think it's a good trick for the basic example in terms of progressive disclosure. 

Those tests are triggered by the master branch's CircleCI config, which just does an additional `git checkout test-code` before running them.

**Comment by bdelacretaz** [comment]
Also created https://github.com/adobe/helix-example-advanced/, as an empty skeleton for now, https://github.com/adobe/helix-home/issues/35

**Comment by bdelacretaz** [comment]
Here's the current status:

* https://github.com/adobe/helix-example-basic/ demonstrates header, footer, Markdown. TODO added to its README for the missing things: CSS override and static HTML
* https://github.com/adobe/helix-example-advanced is a skeleton, the TODO section of its README indicates what it should demonstrate

I think we can close this ticket at this point and create more specific tickets if needed.
