### ISSUE TITLE
helix-pages smoke test service selection is not robust...

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#142]
the test-service is chosen based on the modulo 3 of the circle CI number.
the problem arises if there are several PR running tests in parallel, the CI number doesn't increase sequentially and the chances are high that a PR uses a service already in use.

I don't know of a better solution, though....maybe base the modulo on the PR number instead?

**Comment by trieloff** [comment]
We could just provide more testing services (9) and reduce the risk of collision.

**Comment by tripodsan** [comment]
> We could just provide more testing services (9) and reduce the risk of collision.

better a prime number: 7 or 11.

**Comment by kptdobe** [comment]
With https://github.com/adobe/helix-publish/issues/625, we'll increase the number of test executions, we'll need this one soon. To proceed, we need (assuming we choose X as a prime number 7 or 11)

- [ ] buy the domain names - hlx-<4 to X>.page
- [ ] create the <4 to X> Fastly services
- [ ] add the <4 to X> environment variables (DOMAIN / SERVICE) in https://app.circleci.com/settings/project/github/adobe/helix-pages/environment-variables
- [ ] change the modulo in the config

@trieloff could you take care of the domain names acquisition ? I'll handle the rest. Thx.

**Comment by trieloff** [comment]
Will do.

**Comment by kptdobe** [comment]
From @trieloff : I’ve registered hlx-[4-13].page and onboarded hlx-[4-7].page – the certificates are still being updated

I've created the [4-7] Fastly services and added the env var in helix-pages.
Once certificates are updated, I can change the modulo.
On a side note: because of https://github.com/adobe/helix-publish/issues/625, we'll need to use the CI build number because workflow might start without a corresponding PR number (external call via API)

**Comment by tripodsan** [comment]
hmmm.... we should be able to run any combination of publish, pipeline, action, services against any domain....I think using numbered domain is kind of risky. 

I think using the version-lock it should be possible to create a CI strain and the run the smoke tests against it.

**Comment by kptdobe** [comment]
When done with my comment, I think I understood what you meant: we might need only one domain when we have the version-lock.
But this does not work for publish, we need to fully re-deploy helix-pages "somewhere" before we can use the version-lock on it.

**Comment by kptdobe** [comment]
Same is true for helix-pages code itself, helix-cli too.

**Comment by tripodsan** [comment]
> But this does not work for publish, we need to fully re-deploy helix-pages "somewhere" before we can use the version-lock on it.

yes. but all the tests can happen against the same domain:
- each CI step deploys, using a helix-cli version + pipeline version -> wsk-package
- each CI step creates a strain entry in the `helix-config.yaml`, using that package and using the version-lock information
- the smoke tests run with a `X-Strain` cookie that enforces the strain

**Comment by kptdobe** [comment]
ok makes sense.

> The only thing that cannot be tested reliably using the same fastly service, are multiple versions of a VCL. i.e. changes to helix-publish.

This is being addressed with https://github.com/adobe/helix-publish/issues/625 which needs this one to be sure there is no domain collisions.
