### ISSUE TITLE
Publish npm package for local development

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#15]
helix-cli requires a npm package (https://github.com/adobe/helix-cli/issues/929) so that it can render helix-pages style for default setups.

**Comment by kptdobe** [comment]
FYI, to add `jquery` dependency, I had to introduce a package.json: https://github.com/adobe/helix-pages/blob/master/package.json

**Comment by rofe** [comment]
What do we use jquery for?

**Comment by tripodsan** [comment]
> What do we use jquery for?

see https://github.com/adobe/helix-pages/blob/331b797cee9fa8aeecfb032c6770db49f1740457/src/html.pre.js#L53-L65

**Comment by tripodsan** [comment]
the new approach in helix-cli doesn't need an npm package anymore. I'm going to set it to private.
