### ISSUE TITLE
turn fetch based on fstab into a pipeline step

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pages#151]
I currently had to reuse helix-pages pre.js; and would like to move towards it being put into the pipeline; especially if we want to support word and drive in the long run or in future Helix pages.

We can specify mount-points using a new yaml file;

**Comment by tripodsan** [comment]
@MarquiseRosier do you want to take a stab at this?

**Comment by trieloff** [comment]
Or an f-stab?

**Comment by MarquiseRosier** [comment]
this will definitely sharpen my skills

**Comment by tripodsan** [comment]
fixed with #170
