### ISSUE TITLE
Support cache invalidation / purge

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#17]
If you use helix-pages and request `https://<repo>-<owner>.project-helix.page`, pages get cached while you surf your website. Now, if you change some markdown in the `owner/repo` content repo, a cache purge needs to be done on Fastly. This is not optimal at all and limits the use of helix-pages.
Ideally: when a md file is changed, the corresponding page would be removed from the cache so that on next call, they are re-rendered. It is also expected that pages ESincluding the modified page gets invalidated.
Note that this might require several enhancements in the various Helix stack layers.

**Comment by tripodsan** [comment]
> Note that this will require several enhancements in the various Helix stack layers.

not really, we just need to change the helix-bot that it can detect a helix-pages-content-repo and then send a purge cache request for the respective domain(s).

**Comment by tripodsan** [comment]
btw, you can always purge the cache using the [Purge API](https://docs.fastly.com/api/purge#purge_3aa1d66ee81dbfed0b03deed0fa16a9a).

```
curl -X PURGE https://www.99productrules.com/index.html
```

**Comment by tripodsan** [comment]
But It would be better to purge based on the [surrogate keys](https://docs.fastly.com/api/purge#purge_db35b293f8a724717fcf25628d713583)

As for responses of the pipeline, we already include a surrogate key based on the rendered resource.
But for static requests, we don't.

So the bot should create analyze the modified files, and for each `*.md` compute the surrogate key and then issue a key purge request. for each other modified file, it just send an individual purge request, based on the reverse-computed external url.

**Comment by kptdobe** [comment]
After multiple discussions with @tripodsan and @davidnuescheler, multiple options:

1. use a cookie - if present, always flush the cache when requesting a helix-pages subdomain
2. use a request parameter (`?flush=true`)

Those 2 approaches are wrong because they trigger actions on GET requests. Not desirable.

3. decrease the cache time to 5 mins - when you edit your md, in the worst case, you have to wait 5 mins to see your changes (5 mins minus the time to edit and commit the changes) - quite acceptable and potentially an easy first steps
4. create a polling service that "observes" the repos being served via Helix Pages: when dispatch action is called, it triggers a ping or a post to the polling service to add the current content repo / subdomain to the poll list. Every X mins, the polling services goes through the list of observed repos and fetch the latest commit SHA via the public API: if the latest commit SHA is different from previous time, cache needs to be flushed for that subdomain. If we commit the list of repos + SHA in files, this would also help us to maintain a list of the content repos currently served by Helix Pages.

**Comment by kptdobe** [comment]
I am going to take a quick look at option 3 and try to put it as an extension point in the Helix Pages project.

**Comment by kptdobe** [comment]
If we introduce a VCL extension point (after) for the `vcl_deliver` routine, we could simply add to the helix-pages project extension points:

```
sub hlx_vcl_deliver_after {
   set req.http.Cache-Control = "s-max-age=300";
}
```

to force the cache to be only 5 mins. With the appropriate extension point, this would be an easy solution. The code could be a bit more specific if there are some resources to cache longer.

**Comment by kptdobe** [comment]
Created https://github.com/adobe/helix-publish/issues/123 for the extension point.

**Comment by kptdobe** [comment]
Arff, not so simple, backend requests get strongly cached, need to investigate further.

**Comment by kptdobe** [comment]
Ahah, when using https://fiddle.fastlydemo.net, you get a message: `Caching for only 60 sec? Consider caching things for longer, and purge when they change.` (I defined 60s only for testing). But message is explicit :)

**Comment by davidnuescheler** [comment]
i think initially there is no harm doing just going with no caching until someone installs the bot for invalidation.
it seems to be the simplest solution that could possibly work, can we just try that and see where it goes?

**Comment by kptdobe** [comment]
Ok, so for the pipeline, hooking (i.e. set the `cache-control` header to `no-cache`) into the `pre.js` should do the trick.
@trieloff how do we do that for the static action ? Should we just set the `cache-control` header to `no-cache` directly in the static action code too ?

This would be a quick solution to implement.

**Comment by tripodsan** [comment]
>  just going with no caching until someone installs the bot for invalidation.

@kptdobe we cannot do this on the pipeline or static level. I think this should be done via VCL or experimental-dispatch, since it's dependent on the presence of the bot.

for the helix-pages case, it is not easy to figure out, if the bot is installed; so I would rather stick to the 5 minutes override you suggested. 

I would:
1. if it's not possible to tweak this directly in the VLC, then I add a new _flag_ to experimental dispatch: `cacheControl`.
2. dispatch adds the `Cache-Control` response header accordingly.
3. in VCL, set the `cacheControl=s-maxage=300` or even check for a client request param `noCache` and then set the `cacheControl=no-cache`.

**Comment by trieloff** [comment]
I'd use a VCL-based extension point, as we don't have good extension points in `dispatch` yet. Also, I'd not go with no cache at all, but have a short-lived cache of 1-5 minutes to start.

Finally, as I wrote on Slack, we should try to get support for `Etag`, `If-None-Match` and `304` responses in `dispatch`, based on the results of `resolve-git-ref` lookup.

**Comment by kptdobe** [comment]
@davidnuescheler is pretty strict about the requirements: 
- as an author using Helix Pages for the first times, when you change the content (or the "static" files stored inside your content repo), you must see the changes immediately after page reload in your browser (= no cache!)
- for a "productive" environment (i.e. domain name and authoring "workflow"), the cache is handle as designed initially, i.e the bot purges the cache on content changes

Currently the transition between the first-experience with Helix Pages to I have bot installed is not clear yet. That's probably the first thing to think about.
I also do not like to have specific code in the `pre.js` to handle that, this is just a quick workaround so that @davidnuescheler can move on with selling the concept.
I am going to look at a next iteration with a VCL override. As mentioned in the #54 PR, I think that the Fastly will use the `cache-control` header from the action response to cache the background request accordingly: thus if you expect no-cache of the action executions, the header should not be set. Changing it in the VCL would then too late. But I still need to validate that.
If this is the case, I think your 2 proposals would not work.

**Comment by tripodsan** [comment]
> If this is the case, I think your 2 proposals would not work.

why? the headers are set in experimental-dispatch. but they are only set, if the backend request includes a `cacheControl=no-cache`. and _this_ needs to be enabled only for helix-pages

**Comment by kptdobe** [comment]
AH OK! I understood now.... Then it will work :)

So, to recap:
# via a VCL extension point, Helix Pages sets the `cacheControl=no-cache` flag
# the flag is transported to the exp-dispatch
# if the flag is present, the exp-dispatch sets `Cache-Control=no-cache` instead of the current ones

👍

**Comment by kptdobe** [comment]
With , all resources now get a `Cache-Control` = `max-age=604800, must-revalidate, private` header and are not cached by Fastly (via `Surrogate-Control` = `max-age=0` which is not sent to browser).

While the md changes seem to reliably appear instantly, the css changes need between 0 and several minutes to be detected. Since the file is not cached by Fastly anymore, it should either come from GitHub or something else... need to investigate further. But the dispatch action is doing so many things... hard to debug.

**Comment by kptdobe** [comment]
@davidnuescheler you can starting playing with the cache :)

**Comment by kptdobe** [comment]
The pb is coming from the static action which returns some old content... Really strange, I make an update of the style.css, background color, was blue, then green, then orange. When blue to green, returns green, when green to orange, return blue!!

**Comment by rofe** [comment]
What was the resolution here? Sorry if I missed it...

**Comment by tripodsan** [comment]
We don't cache....
