### ISSUE TITLE
Setup auto-publish

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#2]
- [ ] Setup the CI with secrets to deploy and publish
- [ ] Setup restrictive PR rules
- [x] Don't allow Push to master
- [x] Auto deploy via CI on branch merge to master

**Comment by tripodsan** [comment]
I think we should rather setup CI with the secrets stored there, have restrictive PR rules, don't allow PUSH to master, and auto-deploy via CI....

**Comment by kptdobe** [comment]
Ok makes sense. Updated the title and description.

**Comment by kptdobe** [comment]
For the moment, what's in place:

- commits are blocked on master, PR required (relax policy)
- on merge to master, the CI will deploy and publish
- credentials to who and where are stored in CircleCI and points to: 
  - HLX_WSK_NAMESPACE=acapt
  - HLX_WSK_AUTH=<myauth>
  - HLX_FASTLY_AUTH= <same as project-helix.io>
  - HLX_FASTLY_NAMESPACE=<"helix - Helix Pages - *.project-helix.page" service>

Still todo:
- commit the modified helix-config.yaml after publish
- define proper and dedicated auth token / namespaces
- write tests! nothing garanties that the merge to master is valid code...

**Comment by kptdobe** [comment]
I think this is awesome because we'll break helix-pages often, learn and can make it stronger over time!

**Comment by kptdobe** [comment]
The CI now commit the modified helix-config.yaml using the CircleCi Build token. The process will certainly evolved in the future. Open new issues for next steps.
