### ISSUE TITLE
Master version broken for theblog post pages

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#203]
Open https://theblog--adobe.hlx.page/ms/en/archive/2020/finserv-markets-reduce-time-to-market-by-40-with-adobe-experience-manager.html
-> error 500.

This commit is the source of the issue: https://github.com/adobe/helix-pages/commit/31bfd4ed06d5278cca4feacc559a19b4203771e1

It introduces `"@adobe/helix-pipeline": "6.9.1"` which introduces `"@adobe/helix-epsagon": "1.1.8"`.

Finally, the commit that "seems" to introduce a regression is: https://github.com/adobe/helix-epsagon/pull/35/files.

The latest epsagon version seems to have a conflict with `@adobe/word2md`: it is only when word2md is used that pages are not rendered.

cc @tripodsan @dominique-pfister

**Comment by kptdobe** [comment]
As a tmp fix, I reverted the "published" version of Helix Pages to v1.7.3.

**Comment by kptdobe** [comment]
Humm... I still get 500 errors from time to time. Might still be a timeout issue.

**Comment by rofe** [comment]
Works for me...

**Comment by kptdobe** [comment]
What works for you ? v1.7.4 ?

**Comment by rofe** [comment]
Sorry, I meant the URL above.

**Comment by tripodsan** [comment]
https://github.com/adobe/helix-epsagon/issues/36

**Comment by tripodsan** [comment]
I'm resolving this for now...as the epsagon version is reverted.
