### ISSUE TITLE
Logging: Additional Things to Log to Coralogix

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pages#244]
- [ ] Backend Name
- [x] Request Type
- [x] Strain name

**Comment by trieloff** [comment]
@kptdobe input wanted.

**Comment by kptdobe** [comment]
- [ ] Milliseconds in `cdn.time.start` and `cdn.time.end`

**Comment by trieloff** [comment]
Is the time format ok as is?

**Comment by kptdobe** [comment]
`moment` js could not interpret it as is, I have to provide a custom pattern. I think the issue is that  `seconds` and `GMT` are attached.

**Comment by trieloff** [comment]
Both is easy.

**Comment by trieloff** [comment]
@kptdobe 

```json

{
     "url"  :  "https://theblog-adobe.hlx.page/hlx_950a985490680328f553b6ca5fbff92f09c8bae5.jpg" ,
     "host"  :  "theblog-adobe.hlx.page" ,
     "service_id"  :  "1McGRQOYFuABWBHyD8D4Ux" ,
     "version"  :  "263; src=255; cli=4.4.7; rev=online" ,
     "time"  : {
       "start"  :  "2020-04-21T11:18:37.108+0000" ,
       "start_msec"  :  1587467917108 ,
       "end_msec"  :  1587467917109 ,
       "end"  :  "2020-04-21T11:18:37.109+0000" ,
       "elapsed"  :  634 
    },

```

**Comment by kptdobe** [comment]
Cool!

`cdn.edge.ip_geoip` is broken, it is considered as a property name, not object nested.

**Comment by trieloff** [comment]
`cdn.edge.ip_geoip` is the enriched property that Shuki enabled this morning. I don't think there is anything I can do.

**Comment by trieloff** [comment]
Backend Name is not available, but request type is useful enough. I've also added geolocation (lat, Lon, city and country) for the client IP.
