### ISSUE TITLE
URLs in open graph et al.

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#284]
currently the og meta data looks something like this:

```
 <link rel="canonical" href="https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/30/protect-your-most-sensitive-digital-assets-while-working-from-home.html">
  <meta property="og:url" content="https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/30/protect-your-most-sensitive-digital-assets-while-working-from-home.html">
  <meta property="og:image" content="https://hlx.blob.core.windows.net/external/e6db6c540a6c693f17b4611ffff718968a71f2f7">
  <meta property="og:image:secure_url" content="https://hlx.blob.core.windows.net/external/e6db6c540a6c693f17b4611ffff718968a71f2f7">
  
  <meta name="twitter:image" content="https://hlx.blob.core.windows.net/external/e6db6c540a6c693f17b4611ffff718968a71f2f7">
```

i think that all of the URLs are misleading, most importantly the ones that show the canonical URLs...
ideally they should be something like:

```
 <link rel="canonical" href="https://blog.adobe.com/en/drafts/migrated/2020/04/30/protect-your-most-sensitive-digital-assets-while-working-from-home.html">
  <meta property="og:url" content="https://blog.adobe.com/en/drafts/migrated/2020/04/30/protect-your-most-sensitive-digital-assets-while-working-from-home.html">
  <meta property="og:image" content="https://blog.adobe.coml/hlx_e6db6c540a6c693f17b4611ffff718968a71f2f7">
  <meta property="og:image:secure_url" content="https://blog.adobe.com/hlx_e6db6c540a6c693f17b4611ffff718968a71f2f7">
  
  <meta name="twitter:image" content="https://blog.adobe.com/hlx_e6db6c540a6c693f17b4611ffff718968a71f2f7">

```

i appreciate the complexity with that and wonder what the impact is of just using URLs relative to the host... eg...

```
 <link rel="canonical" href="/en/drafts/migrated/2020/04/30/protect-your-most-sensitive-digital-assets-while-working-from-home.html">

```

i found some conflicting documentation on that but i am not sure if that even works for the `og:` and `twitter:` meta data

**Comment by trieloff** [comment]
Having the hostname in the canonical URL is also useful to prevent accidental double indexing of the various branch versions of the site.

**Comment by rofe** [comment]
I am currently using the URL from the `x-cdn-url` header which I assume to be set in most cases, and fall back to `https://${request.headers.host}${request.url}`. So I think we should be fine for the page URLs in canonical link, og:url and twitter.url. 

For the image URLs, I created https://github.com/adobe/helix-pipeline/issues/706 as I thought this would best be handled in the pipeline.

**Comment by kptdobe** [comment]
If `blog.adobe.com` caches the content for `theblog-adobe.hlx.page`, the of `x-cdn-url` is the latter. I found a `x-hlx-pages-host` header with the front host name (just tested with https://theblog.helix-demo.xyz/). Who sets it ?

**Comment by kptdobe** [comment]
lol. ok, on the same page ;)

**Comment by rofe** [comment]
>  I'm thinking we should align the approaches

Well, looking at the current result, I changed my mind 😄  - now I'm getting `adobeioruntime.net` on the inner CDN and `theblog-adobe.hlx.page` on the outer CDN. Clearly this is going in the wrong direction...

**Comment by florango** [comment]
Now the Helix Pages serves up a canonical URL that points to the adoberuntime page:

<link rel="canonical" href="https://adobeioruntime.net/index.html">

**Comment by rofe** [comment]
I think the `x-forwarded-host` header is almost always backwards and not what we need. We should probably change both sitemap and metadata to use the hostname from the `x-cdn-url` header, and fall back to `request.headers.host`.

**Comment by trieloff** [comment]
Starting with `x-cdn-url` is a good idea. For `x-forwarded-host` we should distinguish between what the spec says (it's useful) and what the the implementation does (it's not). If the implementation changes, then it will be in the direction of increased usefulness.

**Comment by davidnuescheler** [comment]
the canonical URL for everything that doesn't have a `x-cdn-url` header set is still pointing to `*.hlx.page` which is very undesirable from an SEO standpoint, meaning that helix pages can only be found in the `*.hlx.page` domain... 

i appreciate the issue we have with the `x-forwarded-host` we have with the implementation in runtime, so i think in the meantime we should set the `x-cdn-url` header with the value from `x-forwarded-host` if present in the inner CDN. this allows us to shield any other outer cdn from the implementation issues of `x-forwarded-host` in runtime.

**Comment by rofe** [comment]
Now the canonical link href is relative, but the same value is used for `og:url` which doesn't support relative URLs unfortunately...

**Comment by rofe** [comment]
Workaround with relative canonical URL is in place. Revert depends on https://github.com/adobe/helix-publish/issues/451.
