### ISSUE TITLE
Append the query string to ESI includes to work around the cache (temporary solution)

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#29]
Using a cache killer (?x=<new value) in the URL is a good way to work around the strong cache we have on Fastly. Problem is that the ESI includes are always the same thus once header / footer are cached, you need a purge cache on Fastly to have the latest version. 
Until we have a proper solution for #17, we could simple append the query string to ESI includes in order to them to also benefit from the cache killer.

**Comment by kptdobe** [comment]
I implemented and then reverted the solution (final full code is: https://github.com/adobe/helix-pages/tree/esi-cache-killer-debugging). 

I spent half a day looking at the cache issues and here are some insights:

- the simulator and delivery are not behaving the same way: you must enable the query parameter for in production via the `params` property in the helix-config.yaml. See https://github.com/adobe/helix-cli#passing-request-parameters and https://github.com/adobe/helix-simulator/issues/246
- in production, even with the cache killer for the 3 requests (index, header ESI and footer ESI), the content takes hard time to get stabilised to the latest version. See when I increment the counter:
  - https://hlx-demo-kptdobe.helix-demo.xyz/?flush=ASD1 (header.md last version, old index.md)
  - https://hlx-demo-kptdobe.helix-demo.xyz/?flush=ASD19 (old header.md, index.md last version)
  - https://hlx-demo-kptdobe.helix-demo.xyz/?flush=ASD19 (finally both last version)
- while increasing the cache killer, I can see the activations, from a code pov, everything is as expected (the various requests with the same cache killer) but the fetch to git does not seem to lead to the latest version all the time.
- there is clearly a timing dimension, after 10 mins, things are getting more stable (`Cache-Control → s-maxage=604800` ?)
- this does not solve the pb that page without cache killer is still old content

We really need #17 instead of cache killer magic.

**Comment by tripodsan** [comment]
> this does not solve the pb that page without cache killer is still old content
>
> We really need #17 instead of cache killer magic.

#17 will not solve the stale-content from the git repository, but something along the lines of https://github.com/adobe/helix-pipeline/issues/264 will.
