### ISSUE TITLE
make demo projects look great

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#3]
Right now, if you try Helix Pages with a standard `hlx demo`, you get something like this:
![helix-page-demo](https://user-images.githubusercontent.com/1609742/57451437-87f6bf80-7261-11e9-8075-8a36a583a979.png)

**Comment by kptdobe** [comment]
Certain content combinaisons are now properly handled by the htl (like no thematic break - image first which is not full supposed to be fullscreen...). I think this is also linked to multiple issues around `<section>` being generated or not. cc @davidnuescheler

But at least our demo project (a simple markdown page) should be render decently.

**Comment by rofe** [comment]
Actually, after last weeks Helix Pages breakout, I'm not sure if we should still focus on the demo projects, since the demo functionality might even be removed from the CLI...

**Comment by tripodsan** [comment]
well, as soon as we integrate helix-pages into the cli, all demos will look great

**Comment by rofe** [comment]
`hlx demo` is no longer supported.
