### ISSUE TITLE
Image style embed in md file is turned into <img> tag pointing to an html page

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#301]
Complex to explain but:

https://adobe.sharepoint.com/sites/TheBlog/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000291CC2F215041D41ADE01F0A04AB94F2&id=%2Fsites%2FTheBlog%2FShared%20Documents%2Ftheblog%2Fen%2Fdrafts%2Fmigrated%2F2020%2F04%2F30%2Fprotect%2Dyour%2Dmost%2Dsensitive%2Ddigital%2Dassets%2Dwhile%2Dworking%2Dfrom%2Dhome%2Emd&parent=%2Fsites%2FTheBlog%2FShared%20Documents%2Ftheblog%2Fen%2Fdrafts%2Fmigrated%2F2020%2F04%2F30&p=5

This `md` file renders as https://theblog--adobe.hlx.page/en/drafts/migrated/2020/04/30/protect-your-most-sensitive-digital-assets-while-working-from-home.html

It contains some broken images. 

Source: `![](https://www.youtube.com/embed/gf_vYvKmfsg)` (valid per https://github.com/adobe/helix-pipeline/blob/54abdb9f35e47e8ea2a5021e0739f15881daac81/docs/markdown.md#image-style-embeds)
Generated DOM: `<img src="/hlx_49747a0756f1cb14ecd925cabb6a9b45599e24a8.html">`

**Comment by kptdobe** [comment]
I suspect word2md - cc @tripodsan

**Comment by rofe** [comment]
This appears to be valid image-style embed notation:
https://github.com/adobe/helix-pipeline/blob/master/docs/markdown.md#image-style-embeds

**Comment by MarquiseRosier** [comment]
Right; it looks like these aren't working for any embeds

https://theblog--adobe.hlx.page/en/drafts/migrated/2020/04/29/10-brands-that-shifted-their-advertising-strategy-amid-covid-19.html

But mine works: 
https://embeddingcheck-marquiserosier.hlx.page/g/index2.html

**Comment by tripodsan** [comment]
fixed.
