### ISSUE TITLE
Keep robots out on the inner CDN

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#326]
Customer projects based on Helix Pages typically have an outer CDN with their own domain name, caching. That is the site they want to see indexed by Google et al. The inner CDN (*.hlx.page) should on the other hand always be left alone by robots.

**Comment by trieloff** [comment]
The easiest way of building this would be placing a default `robots.txt` in `helix-pages`.

**Comment by rofe** [comment]
BREAKING CHANGE: Add a robots.txt to your Helix Pages project to enable crawling and indexing.

**Comment by rofe** [comment]
I am reopening this because the current solution turned out to be a bit impractical: as a customer, I can't just add my own robots.txt to the project repo, because it would allow crawlers to index the inner CDN as well. So I have to resort to exotic ways of delivering the project specific robots.txt files on the outer CDN (i.e. using a Fastly rule).

After dicussing with @trieloff, I'd like to change the implementation to remove the static robots.txt again and instead add a rule to the Helix Pages Fastly service which delivers a synthetic non-permissive robots.txt in case there is no `x-forwarded-host` header set (i.e. on the inner CDN).
