### ISSUE TITLE
changes in pipeline handling of images broke default layout

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#40]
as small change introduced by https://github.com/adobe/helix-pipeline/issues/338 seems to have broken some of the correct mapping to the `image` class as the selector in `html.pre.js` doesn't seem to apply anymore.

instead of rendering like this...

<img width="1227" alt="Screen Shot 2019-06-19 at 11 08 00 AM" src="https://user-images.githubusercontent.com/5289336/59789377-a6999e80-9282-11e9-867d-68837f4e1fa3.png">

the most recent helix-cli renders like this...

<img width="1227" alt="Screen Shot 2019-06-19 at 11 08 18 AM" src="https://user-images.githubusercontent.com/5289336/59789440-b7e2ab00-9282-11e9-821f-e73c936b957b.png">

**Comment by craeyu** [comment]
issue fixed
