### ISSUE TITLE
ignore/strip query params for html pipeline

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#402]
as we don't assume server sided extensibility i think it would be great if we could just ignore query params at least in the default outer cdn setup that could yield better cache performance.

this is particularly important, where links are passing in query parameters that are used on the client-side only for analytics purposes or to customize a the page in other ways.

of course we need to be careful in areas where we use the query parameters eg. the '.json' pipeline or someo of our font and image proxies.

**Comment by trieloff** [comment]
Here is how I'd like to implement this:

In https://github.com/adobe/helix-pages/blob/fb53660b8f84df4df216593b048ed09f9ce38fcc/vcl/extensions.vcl#L14 make the disabling of the Dispatch cache conditional on the value of the `X-Forwarded-Host`. 

If XFH includes domain names other than the helix-pages domains, keep the cache enabled. 

The default helix VCL already does strip query parameters (except for request types where they are needed) and I don't want to duplicate this in the outer CDN.
