### ISSUE TITLE
helix pages default markup (html.pre.js) breaking change and refactor

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#403]
after using our standard markup for a while now, i realized that i would like to remove the `title` and `header` treatment as well as the `image` and `default` classes altogether. 

they seem largely useless and arbitrary, considering the amount of page decoration of the DOM we usually do on the client side.

as this has pretty sizable implications on every helix pages project, we should probably do this sooner than later.

looking at the current `html.pre.js` this would probably also mean that we could remove jquery as a dependency.

i think it would be great to supply a client-sided helper for the projects that relied on the current behaviour.

i am assigning this to @rofe as the remainder of the `html.pre.js` is largely his work.

**Comment by rofe** [comment]
Started a draft PR but will wait for @kptdobe's input since he was the original author of the logic to be removed.

**Comment by rofe** [comment]
Fixed in https://github.com/adobe/helix-pages/releases/tag/v4.1.0
