### ISSUE TITLE
make internal embed wrapping div more addressable with css classes

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#408]
**Is your feature request related to a problem? Please describe.**
currently the embed, specifically for internal embeds (eg. `/components/mycomponent.html`) just includes a plain `div`. while that's relatively easy to handle in the case of the embed being backed by an actual `.md` it becomes a lot more complicated to do when the embed comes from a gdoc or `.docx`

**Describe the solution you'd like**
i really like the classes we put on to icons that come via the `:icon:` syntax.
so eg. for something like `:twitter:` we have a the following classes `class="icon icon-twitter"`.
in that light i could see something like `class="embed embed-mycomponent"`

**Comment by tripodsan** [comment]
I also think that we should address this in pipeline (2)..... why did you move it to helix-pages ?

**Comment by trieloff** [comment]
Sorry, I mistyped. I think (1) is the better approach because it leaves the default HTML more compact and less opinionated. When I spoke with @davidnuescheler, he agreed.
