### ISSUE TITLE
circleci publish step fails

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-pages#409]
helix-pages config.yaml for circleci seems to fail at the publish step pretty frequently. This leads us to not receive necessary changes to fix problems showing up in places like theblog, etc. Is there a way we can make this fail less frequently?

**Comment by MarquiseRosier** [comment]
@trieloff @rofe would love your feedback on this

**Comment by trieloff** [comment]
What are the most common errors we are seeing?

**Comment by MarquiseRosier** [comment]
It's between an unauthorized error which I suspect is coming from hlx publish and this kind

<img width="1382" alt="Screen Shot 2020-07-30 at 12 41 28 PM" src="https://user-images.githubusercontent.com/12217245/88967014-12aa4c80-d262-11ea-9af3-87fc612f6398.png">

**Comment by trieloff** [comment]
The error above looks much like https://github.com/adobe/helix-publish/issues/549

**Comment by rofe** [comment]
@MarquiseRosier I remember having to re-run CI jobs in helix-pages because of intermittent failures in smoke tests from other repos...

**Comment by tripodsan** [comment]
closing for now.
