### ISSUE TITLE
proposing to wrap sections into <main>

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#41]
looking at some of the dom manipulations and usage of selectors it may both be semantically correct and more convenient to wrap the sections into a `<main>` tag which, also seems to be symmetrical to the use of `<header>` and `<footer>`

**Comment by anfibiacreativa** [comment]
Please keep in mind that semantic html elements are not supported by some browsers (notably IE11, which still has a considerable share especially amongst enterprise users). And considering we don't know the potential support matrix in an X requirement, developers should have the ability to add a second wrapper below those, to ensure correct styling and potentially add aria landmarks

**Comment by davidnuescheler** [comment]
that's a good point. 

i don't have an IE11 handy but from what i read, the main element can still be used and styled in IE11, i think the only difference is that there is no user-agent supplied style for the main element in IE11, meaning that it doesn't default to `display: block`. 
do you think that's correct? 
does someone have an IE11 handy to test the potential impact for the output of helix-pages rendering?

a developer can alter the dom in helix-pages by injecting elements on the client side, while in helix proper of course the entire markup can be manipulated, but more generally we should probably document our browser support for helix-pages. i'll open issue for discussion.
