### ISSUE TITLE
default meta image should be a jpg

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#411]
i would argue that in most cases the images that make sense as meta images are photos... i think the current image is a good example of what looks weird, so i would recommend to have the default be a jpg, instead of a png.

check for example this one:
https://staging--pages--adobe.hlx.page/default-meta-image.png

**Comment by rofe** [comment]
I totally agree that the meta image should be a photo whenever possible, and Helix Pages will always try to extract a suitable one from the page content. The default meta image is only used in the special case where Helix can't find one (e.g. on a homepage), so I figured what customers would want to put there in that case will be a logo of sorts. Something a lossy format like jpg usually isn't that great for (transparency would be an added bonus, but probably not used that much). 

I think the CC logo is among the 1% of logos where a jpg would work better than png :)

Having been on the fence from the start, I'm fine switching to jpg, but I'm a bit worried about backward compatibility, or unnecessary complexity if we want to keep support for both. 

I know it's an ugly workaround, but what's stopping them from using a jpg posing as a png?

**Comment by rofe** [comment]
@davidnuescheler wdyt?
