### ISSUE TITLE
Forward surrogate-key header

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#425]
The `surrogate-key` header from the backends should be forwarded to the response of the inner CDN (*.hlx.page).
This will allow cache purging of a potential outer (fastly) CDN.

**Comment by tripodsan** [comment]
@trieloff any advice how to add this to the extensions.vcl ?

**Comment by trieloff** [comment]
I've tried adding it to the VCL snippets, so that we don't have to touch extensions, but it's not working yet.

**Comment by tripodsan** [comment]
I changed the snippet to:

```
set resp.http.Surrogate-Key = req.http.Surrogate-Key;
```

and now it works:

```
$ curl -sD - https://theblog--adobe.hlx.page/en/publish/2020/06/10/listening-learning-and-taking-action.html
HTTP/2 200
cache-control: max-age=604800, must-revalidate, private
content-type: text/html; charset=UTF-8
link: <https://theblog--adobe.hlx.page/en/publish/2020/06/10/listening-learning-and-taking-action.html>; rel="canonical"
x-frame-options: deny
date: Thu, 13 Aug 2020 01:40:40 GMT
vary: X-Debug,X-Strain,X-Request-Type,X-Forwarded-Host
surrogate-key: all 4+2mhPKWJKFQQH+u PSD2f0yIE76zdMys
strict-transport-security: max-age=31536000
x-version: 396; src=389; cli=6.3.2; rev=online
content-security-policy: frame-ancestors 'self'

<!DOCTYPE html><html>
...
```

**Comment by tripodsan** [comment]
I don't know why the 'Stash Surrogate-Key` didn't work... but I think we can delete that snipped

**Comment by trieloff** [comment]
@tripodsan should we do this by default in helix-publish when an outer CDN is present?

**Comment by tripodsan** [comment]
> @tripodsan should we do this by default in helix-publish when an outer CDN is present?

is there a way to detect this?

**Comment by trieloff** [comment]
Yes, based on the XFH header.
