### ISSUE TITLE
init_smoketests fail - node process is killed

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-pages#498]
`init_smoketests` are currently failing in the `Deploy to Adobe I/O Runtime` step ([example](https://app.circleci.com/pipelines/github/adobe/helix-pages/1999/workflows/ab32fc22-51c0-4f6f-a9a4-2ebb8950262f/jobs/7593)). Apparently, the node command:
```
npx hlx deploy --wsk-action-memory 512 ...
```
is killed by the system because it runs out of memory. Having `top` running in parallel shows that the `RES` size of the node process reaches 3.9G right before it is killed (max memory for that docker image is 4GB).

Debugging on a SSH accessible CircleCI Docker image reveals that the crash happens in [GitUtils.getBranch](https://github.com/adobe/helix-cli/blob/9c7e7e1980a03a1f541b2a3a37e8bada844e1f18/src/git-utils.js#L139)  in `helix-cli`: there are 414 tags to be examined, and the execution never returns from `isomorphic-git.readObject()`.

If I manually decrease the number of tags being inspected to 150, `npx hlx deploy` succeeds, it starts breaking at around 200 tags. 

If I turn the `await Promise.all(allTags.map(...))` into a for loop, the issue no longer occurs.

Things I already tried without success:
- running the node process with more memory (NODE_OPTIONS=--max-old-space-size=...) 
- pinning the docker image version used by the last [successful build](https://app.circleci.com/pipelines/github/adobe/helix-pages/1994/workflows/83c3005b-cd3e-4284-9e38-9646afecc268)
- increasing the docker image's size to large (8 GB RAM/4 vCPUs)

**Comment by dominique-pfister** [comment]
Looks like the node process is running out of memory: looking at the `RES` size in `top` of the node process, it is killed when it surpasses 3.9G (max memory for that docker image is 4GB).

If I manually decrease the number of tags being inspected to 150, `npx hlx deploy` succeeds, it starts breaking at around 200 tags.

**Comment by dominique-pfister** [comment]
Create an issue in isomorphic-git: https://github.com/isomorphic-git/isomorphic-git/issues/1241

**Comment by stefan-guggisberg** [comment]
The underlying issue has been fixed in `helix-cli` via https://github.com/adobe/helix-cli/pull/1543. 

This issue should be fixed once the above fix has been released.
