### ISSUE TITLE
[default styling] suppress layout shift

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#512]
currently on the initial load (eg. hlx.page) the default design shows a layout shift.
i think it would be nice to suppress that with an `opacity: 0` on `main` that is replaced with an `opacity: 1` and a swift 200ms animation after the page is decorated.

this really is only visible in the uncached origin, but would be nice anyway

**Comment by spenhar** [comment]
Noticed that today, nice eye! Definitely a nice to have.

**Comment by rofe** [comment]
I would not animate it, otherwise page refreshes will flicker.
