### ISSUE TITLE
Static files updates are not tested

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#513]
This is a pretty critical issue.

While debugging for https://github.com/adobe/helix-pages/issues/493, I realised the test domains published by the CI (hlx-1...) do not render the branch version of the static files (head.html in that case).

To test (need to validate): 
- create a helix-pages branch
- change the `head.html`
- commit
- go to CircleCI and wait for the `init_smoketests` job of that branch to be finished
- expand the `Compute TEST_DOMAIN and TEST_SERVICE` step and note the test domain where the deployment has been made (hlx-X)
- request `https://www.hlx-X.page/head.html`

In order for the tests to be meaningful, this must be the one from the branch. But you still get the master one.
I assume the `hlx publish` we do in the CI must be configure to add a strain pointing to the branch as a content and static repo.

I can look into it but maybe @trieloff @tripodsan you have some ideas to share.

**Comment by trieloff** [comment]
Editing helix-config.yaml prior to Publishing might be enough. Just include the current branch name.

**Comment by kptdobe** [comment]
Not so easy, of course!

Changing the `helix.config.yaml` is correct but reveals 2 issues:
- how do we determine the default branch of the customer site being requested ? `theblog--adobe.hlx-1.page` implicitly refers to `master` in `theblog/adobe` repo.
- once this is set, how do we determine the fallbacks ? `theblog--adobe.hlx-1.page/head.html` might either be `theblog/adobe#master/head.html` if exists or fallback to `helix-pages/adobe#my-wip-pr/head.html`

The overall chain is mixing 2 things:
- helix-pages `owner` / `repo` / `ref`
- customer site `owner` / `repo` / `ref`

With extension.vcl, we allow to override the `owner` / `repo` / `ref` but we do not specify a default `ref` (https://github.com/adobe/helix-pages/blob/master/vcl/extensions.vcl#L88-L96). Thus the helix-pages `ref` will be used for the customer site.

A strain contains 3 info:
- the code `owner` / `repo` / `ref`
- the content `owner` / `repo` / `ref`
- the static `owner` / `repo` / `ref`

while the code cannot be changed, the content and static would have be overridden by the customer site info from the url (including a fallback to the appropriate `ref` in that repo) and the VCL should keep a record of the initial values because this is were the fallback should happen. I am even not sure if this is not something that would need to be propagated to `helix-dispatch`.

**Comment by tripodsan** [comment]
but isn't the pages repo for the static files, the code-repository, where as the customers repo for their static files, is the content-repository ?

**Comment by kptdobe** [comment]
Maybe. I am currently extending my Trace&Debug tool to be able to visualise what is being really used.
