### ISSUE TITLE
Meta image URL should use Fastly IO

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#541]
The meta image URL is currently using the original first image on a given page, which can be quite large. Slack is reluctant to expand the preview if the image file size is too large, other sharing platforms might even refuse to do so.

We should use Fastly image optimization query parameters to reduce the file size and display the image at the optimal ratio based on the metadata specs (og, twitter).

cc @davidnuescheler

**Comment by davidnuescheler** [comment]
great idea... a quick online research revealed that there seems to be a rough consensus between insta, fb, twitter and linkedin suggests that 1200px width seems to be the widest and a 1.91:1 aspect ratio seems to be common.

so something like 

https://blog.adobe.com/hlx_4a0ffbe8665ff1fdd9f21dd6c317812de3207c01.jpeg?auto=webp&format=pjpg&optimize=medium&width=1200&crop=1.91:1 

...could be ok, but could be too restrictive for portrait images, so maybe something like...

https://blog.adobe.com/hlx_4a0ffbe8665ff1fdd9f21dd6c317812de3207c01.jpeg?auto=webp&format=pjpg&optimize=medium&width=1200
