### ISSUE TITLE
Sidekick: share settings button

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pages#571]
Let's add a "share sidekick" button that shares a link to the hlx.page/sidekick URL with the same parameters used to set up the sidekick in the first place. This button should use the [Web Share API](https://web.dev/web-share/) and help with the distribution of sidekick configs in a project.

**Comment by rofe** [comment]
Do you mean a share button on the sidekick configurator page, or in the sidekick itself?

**Comment by trieloff** [comment]
In the sidekick itself. After setting up the sidekick once it is easy to forget about the settings, and the most common case where you need them is to share the exact setup with a team member.

**Comment by rofe** [comment]
![image](https://user-images.githubusercontent.com/1609742/100485118-380b7200-30ff-11eb-97f7-82502b017801.png)
