### ISSUE TITLE
Sidekick: doesn't open on md file

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#590]
in the _view_ mode of an MD file in sharepoint, the sidekick doesn't open when you click the bookmarklet.
once the MD file is opened in the sharepoint text editor, the sidekick opens.

**Comment by rofe** [comment]
I think that's ok, though, no? The other way round, the Edit button will take you to the text editor, not the view mode.

**Comment by rofe** [comment]
Cannot reproduce with latest version.

**Comment by kptdobe** [comment]
I still cannot view the sidekick in _view_ mode. But I found why: Sharepoint UI has a pretty large z-index: `1000000`!
We just need to go above that!
