### ISSUE TITLE
diff tests should upload html as artifacts

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#637]
sometimes the diff tests fail for no apparent reason. i.e. when you donwload the requested content manually and compare the versions, they are _identical_. so maybe something went wrong the first time circleci requests the pages.

In order to see what was actually fetched, the responses should be saved to disk and then uploaded as artifacts to the job.

**Comment by kptdobe** [comment]
With https://github.com/adobe/helix-pages/issues/525 you should see the junit diff result (the + and -) in the task execution. This should be enough to view the diff.

**Comment by tripodsan** [comment]
@kptdobe so where is this information here: https://app.circleci.com/pipelines/github/adobe/helix-pages/2758/workflows/2dca3f7b-3f3a-4d62-9d5e-170acb3f7323/jobs/12026/steps ??

**Comment by kptdobe** [comment]
ahh... this is an edge case: it is not the test that fails but the parsing of the DOM. See https://github.com/adobe/helix-shared/issues/412
We could certainly add a `try/catch` and print a meaningful `console.log` if something goes wrong before the tests.

**Comment by tripodsan** [comment]
no longer needed as test steps reveal a good diff now. thanks @kptdobe !

**Comment by kptdobe** [comment]
The diff test is not enough in certain cases. I will upload the html as artifacts.
