### ISSUE TITLE
Breaking *: use custom pipeline

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#639]
(not really a breaking change, but might help to implement #638)

When transitioning towards a helix-pages service, having a lot of functionality _hidden_ in helix-pipeline makes it intransparent. Having a leaner pipeline that doesn't do much magic and have this magic added to this repository makes it easier to develop.

the current default html pipeline defines the following (non mandatory) steps:

```
    .use(fetchMarkupConfig)
    .use(fetchContent).expose('content').when(hasNoContent)
    .use(fetch).expose('fetch').when(hasNoContent)
    .use(parse).expose('parse')
    .use(embeds)
    .use(dataEmbeds)
    .use(smartypants)
    .use(iconize)
    .use(sections)
    .use(rewriteBlobImages)
    .use(meta).expose('meta')
    .use(unwrapSoleImages)
    .use(adjustMDAST)
    .use(selectstrain)
    .use(selecttest)
    .use(dataSections)
    .use(html).expose('html')
    .use(adjustHTML)
    .use(sanitize).when(paranoid)
    .use(cont)
    .use(type('text/html'))
    .use(cache).when(uncached)
    .use(key)
    .use(tovdom).expose('post') // start HTML post-processing
    .use(removeHlxProps).expose('cleanup')
    .use(rewriteLinks).when(production)
    .use(addHeaders)
    .use(tohtml) // end HTML post-processing
    .use(flag).expose('esi').when(esi) // flag ESI when there is ESI in the response
```

As a first step, helix-pages should define its own pipeline as a copy of the default html pipeline.

Next steps could be to _move_ some of the more project specific steps to helix-pages, eg
- iconize
- sections (see #640)
- disable: embeds

**Comment by rofe** [comment]
@tripodsan should we defer this to the next breaking branch?

**Comment by tripodsan** [comment]
> @tripodsan should we defer this to the next breaking branch?

it wasn't really a breaking change anyways.... since for the customer, the output stays the same.
