### ISSUE TITLE
Breaking March: double section divs

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#640]
for styling purposes, it is often much more easy if a section would have 2 divs. one for the background image/color and one for the actual content.

suggest to add this as pipeline step to helix-pages (and not to helix-pipeline)

/cc @davidnuescheler

**Comment by tripodsan** [comment]
@davidnuescheler should the class name be on the outer, inner or both divs?

i.e.:

```
outer:

<div class="test">
  <div>....section content...</div>
</div>


inner:

<div>
  <div class="test">....section content...</div>
</div>


both:

<div class="test">
  <div class="test">....section content...</div>
</div>

```

**Comment by kptdobe** [comment]
With `inner` config, you cannot specifically address the parent div with css.
`both` is weird and same result can be achieved with the `outer` config (`.text > div`).
But @davidnuescheler might see something else.

**Comment by tripodsan** [comment]
> With `inner` config, you cannot specifically address the parent div with css.

true.. I implemented the `outer` case:
https://github.com/adobe/helix-pages/blob/80c5bd0445ab8e8f72168175690de0d7215e7565/test/unit/fixtures/one-section.html

**Comment by davidnuescheler** [comment]
i don't think there is a natural way to in (gdocs/word) authoring to provide any classes for sections, so i don't think we should add classes. in turn this leads me to think that we shouldn't implement the double section divs, until we found a good way to represent classes for sections and leave them on the client side for now...

sorry for flip-flopping on this one, but i think it is best to postpone this one for after march.

**Comment by tripodsan** [comment]
> in turn this leads me to think that we shouldn't implement the double section divs

what about in the page blocks? there we know the class. should we add double divs?

**Comment by tripodsan** [comment]
closing won't fix.
