### ISSUE TITLE
Reactivate Universal Strain

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pages#675]
@rofe do you know which status check @tripodsan refers to in https://github.com/adobe/helix-pages/commit/eecb5419ace63fc4f04f557463a92952a9ca5fb2 ?

Helix Publish is ready enough for some testing, I have seen both the blog and pages being served from Lambda on a test domain.

**Comment by tripodsan** [comment]
it was the status check in helix-publish that tests if HTML actions of all strains work.
