### ISSUE TITLE
Closing slash of the meta properties gets lost

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#692]
Our source code defines the meta tag as `<meta ... />` but they get rendered as `<meta>`

Source: https://github.com/adobe/helix-pages/blob/master/src/html.htl#L5-L22
Output: [view-source:https://blog.adobe.com/en/publish/2021/02/01/adobe-leader-2021-gartner-digital-experience-platforms-magic-quadrant.html](view-source:https://blog.adobe.com/en/publish/2021/02/01/adobe-leader-2021-gartner-digital-experience-platforms-magic-quadrant.html)

The blog article DOM contains the meta tags rendered by Helix WITHOUT the closing slash AND some meta tags defined in the [head.html](https://github.com/adobe/theblog/blob/master/head.html#L1-L9) WITH the closing slash. 

It would be much better to respect the predefined HTL to harmonise the output.

@tripodsan Do you think this is an HTL engine issue or more on the pipeline side ?

**Comment by trieloff** [comment]
Meta tags do not need the closing slash, so anything that goes through JSDOM will omit/strip them. This includes both pipeline and htlengine.

helix-static does not do any HTML post-processing (yet), so it won't normalize them.

**Comment by tripodsan** [comment]
closing won't fix.
