### ISSUE TITLE
statics not loading with version lock set

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#713]
### Expected Behaviour
Static files from [htdocs](../tree/master/htdocs) should load fine regardless of version lock.

### Actual Behaviour
Static files return `404` if a `helix-version.txt` is present.

### Steps to Reproduce
1. Create a public repo with an `index.html`
2. Open `https://<repo>--<owner>.hlx.page/`
3. Page renders fine, no `404s` in the browser console
2. Add a `helix-version.txt` with `breaking-202103`
3. Reload `https://<repo>--<owner>.hlx.page/`
4. Page rendering is broken due to missing scripts and styles

<img width="887" alt="Screenshot 2021-02-24 at 10 57 45" src="https://user-images.githubusercontent.com/1609742/108983448-2b130600-768f-11eb-9a06-67b4c80381e2.png">

**Comment by rofe** [comment]
@tripodsan could you take a look please?

**Comment by tripodsan** [comment]
I'm still struggling to get the setup done.... for some reason, the breakinh-202103 is not beeing picked up
