### ISSUE TITLE
Sidekick: publish to purge path with and without .html extension as well as .md

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#718]
The default preview URL is now extensionless, but the sidekick should still purge URLs with and without .html extension.

cc @davidnuescheler

**Comment by tripodsan** [comment]
@rofe can we also purge the `.md` ?

**Comment by rofe** [comment]
I just realized that we were already doing the _with and without `.html` extension_ part in `helix-purge` (see https://github.com/adobe/helix-purge/issues/12), which means we are now double-purging those URLs. While reverting this change in the sidekick, I'm inclined to also move the _as well as `.md`_ part to `'helix-purge` in order to minimize the number of requests sent from sidekick.

@tripodsan @trieloff wdyt?

**Comment by rofe** [comment]
See https://github.com/adobe/helix-purge/issues/128 and #731
