### ISSUE TITLE
version lock for spark-website--adobe.hlx.page causes diff test to fail

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pages#724]
First seen in https://github.com/adobe/helix-publish/pull/760 now also blocking the build for #721 , #723

The Spark website is using the new `helix-version.txt` feature, which gets picked up correctly by `hlx.page` but fails for `hlx-*.page`. This causes differences in the generated HTML, which causes the diff test to fail.

**Comment by trieloff** [comment]
According to investigations in https://github.com/adobe/helix-publish/pull/760 the strain resolution works as expected, `X-Strain: breaking-202103` for all requested variants.

On `hlx.page`: `X-Backend-URL: /api/v1/web/helix-pages/helix-services/dispatch@v4?static.owner=tripodsan&static.repo=helix-pages&static.ref=breaking-202103&static.root=/htdocs&content.owner=adobe&content.repo=spark-website&content.ref=master&content.root=&content.package=pages_4.16.14.breaking-202103&content.index=index.html&path=/make/add-music-to-video&strain=breaking-202103&rootPath=&params=`

On `hlx-4.page`: `X-Backend-URL: /api/v1/web/helix-pages/helix-services/dispatch@v4?static.owner=tripodsan&static.repo=helix-pages&static.ref=breaking-202103&static.root=/htdocs&content.owner=adobe&content.repo=spark-website&content.ref=master&content.root=&content.package=pages_4.15.4.breaking-202103&content.index=index.html&path=/make/add-music-to-video&strain=breaking-202103&rootPath=&params=`

There is a mismatch between `content.package=pages_4.16.14.breaking-202103` (hlx.page) and `content.package=pages_4.15.4.breaking-202103` (hlx-4.page) which looks like an issue with manual deployment.

**Comment by trieloff** [comment]
According to investigations in https://github.com/adobe/helix-publish/pull/760 the strain resolution works as expected, `X-Strain: breaking-202103` for all requested variants.

On `hlx.page`: `X-Backend-URL: /api/v1/web/helix-pages/helix-services/dispatch@v4?static.owner=tripodsan&static.repo=helix-pages&static.ref=breaking-202103&static.root=/htdocs&content.owner=adobe&content.repo=spark-website&content.ref=master&content.root=&content.package=pages_4.16.14.breaking-202103&content.index=index.html&path=/make/add-music-to-video&strain=breaking-202103&rootPath=&params=`

On `hlx-4.page`: `X-Backend-URL: /api/v1/web/helix-pages/helix-services/dispatch@v4?static.owner=tripodsan&static.repo=helix-pages&static.ref=breaking-202103&static.root=/htdocs&content.owner=adobe&content.repo=spark-website&content.ref=master&content.root=&content.package=pages_4.15.4.breaking-202103&content.index=index.html&path=/make/add-music-to-video&strain=breaking-202103&rootPath=&params=`

There is a mismatch between `content.package=pages_4.16.14.breaking-202103` (hlx.page) and

**Comment by trieloff** [comment]
https://github.com/adobe/helix-pages/blob/1bc2c5d874755fd8e28655626cab08f981fce3cf/helix-config.yaml#L49

has the 4.15.4 version

https://github.com/adobe/helix-pages/blob/a23b2b299fce1b3a57a0235a1102afc392f6644a/helix-config.yaml#L49

has the 4.16.4 version

so the issue is that the `helix-config.yaml` between `master` and `breaking-*` is getting out of sync. In my mind, `breaking-*` should 

1. fetch the latest `helix-config.yaml` from `master`
2. run `hlx deploy && hlx publish --only`
3. merge the updated `helix-config.yaml` back into `master`

I will update the version in `master` manually for now.

**Comment by trieloff** [comment]
```
error: Remote publish service failed Error: 400 - "{
  "message": "Error: Status check for strain breaking-202103 failed when invoking https://adobeioruntime.net/api/v1/web/***********/pages_4.16.4.breaking-202103/html/_status_check/healthcheck.json: 404 {\n  \"code\": \"PH5VEgjzcsOSe6wceWoBScaVURDIXOCE\",\n  \"error\": \"The requested resource does not exist.\"\n}",
  "stack": ["Error: Status check for strain breaking-202103 failed when invoking https://adobeioruntime.net/api/v1/web/***********/pages_4.16.4.breaking-202103/html/_status_check/healthcheck.json: 404 {", "  \"code\": \"PH5VEgjzcsOSe6wceWoBScaVURDIXOCE\",", "  \"error\": \"The requested resource does not exist.\"", "}", "    at checkStrains (/nodejsAction/HfuFjMRS/main.js:70346:11)", "    at processTicksAndRejections (internal/process/task_queues.js:97:5)", "    at async Promise.all (index 4)", "    at async publish (/nodejsAction/HfuFjMRS/main.js:71458:5)", "    at async /nodejsAction/HfuFjMRS/main.js:7219:14", "    at async /nodejsAction/HfuFjMRS/main.js:7357:15", "    at async /nodejsAction/HfuFjMRS/main.js:25164:24"],
  "status": "invalid configuration"
}"
```

dang it! fixed in e55112b

**Comment by tripodsan** [comment]
should be fixed with new script:
https://github.com/adobe/helix-pages/blob/a23b2b299fce1b3a57a0235a1102afc392f6644a/release/publish.sh#L35-L53

**Comment by tripodsan** [comment]
closing.

**Comment by trieloff** [comment]
Has the script been merged and activated?

**Comment by tripodsan** [comment]
> Has the script been merged and activated?

the breaking branch is using the `publish.sh`, yes. the master doesn't yet.
