### ISSUE TITLE
helix-cli local development with fstab / google drive

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-pages#73]
currently i am getting an error when trying to develop a helix pages project locally that has a reference to a google drive folder.

```
[hlx] warn: google docs mountpoint needs a configured GOOGLE_DOCS_ROOT but is missing.
```

**Comment by davidnuescheler** [comment]
@kptdobe just pointed me here:
https://github.com/adobe/helix-pages#manual-testing-with-google-docs-support

i think this could be enabled/configured by default for helix-pages, especially as the fstab functionality is enabled by default, and the only `fs-type` supported is google right now...

**Comment by tripodsan** [comment]
I wasn't sure how secret the google web app path is, so I made it configurable.
but after reading up https://developers.google.com/apps-script/guides/web I don't think its secret beyond the potential DOS attack vector.

options:
1. add the web app url as default in the code
2. create a very simple runtime action that just invokes the webapp. so we can hard code the action url instead
3. configure a backend in fastly that forwards the request to google.

@davidnuescheler @trieloff  WDYT?
