### ISSUE TITLE
rendering for plain.html is missing divs

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#748]
currently there is no special treatment for `...plain.html` (no sections, no blocks, no image handing, etc)

should we enable those, too?

**Comment by tripodsan** [comment]
there is a difference already for a md that has only 1 _section_. in this case there is no div around):

eg:
```md
---
class: test
---

# Hello

This is the first section.
```

is rendered as:

```html
<h1 id="hello">Hello</h1>
<p>This is the first section.</p>
```

---

but if there are more sections:

```md
# Hello

This is the first section.

---
class: test
---

## Foo

Here comes the 2nd section

---

and the last :-)
```

it's rendered as:

```html
<div>
    <h1 id="hello">Hello</h1>
    <p>This is the first section.</p>
</div>
<div class="test">
    <h2 id="foo">Foo</h2>
    <p>Here comes the 2nd section</p>
</div>
<div>
    <p>and the last :-)</p>
</div>
```

**Comment by davidnuescheler** [comment]
I think .plain.html need to have the same treatment as .html otherwise some of our uses don't work any more.

**Comment by tripodsan** [comment]
> I think .plain.html need to have the same treatment as .html otherwise some of our uses don't work any more.

this would also mean, that for example an empty `haeder.md` would be included with a single `<div></div>`, if we treat it the same.
