### ISSUE TITLE
Diff tests seems to compare html from other branches

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#790]
Some sites are configured to use a custom helix-pages branch via the `helix-version.txt` file.

See example: https://github.com/davidnuescheler/embrew/blob/master/helix-version.txt
When requesting https://embrew--davidnuescheler.hlx.page/, you get a version of the site that uses the `breaking-202103` helix-pages branch.

When a PR against `master` is created in helix-pages, we compare the current branch code to various sites with the assumption that the helix-pages branch used there is `master`. But with the `helix-version.txt` feature, this assumption could be wrong.

We need to extend the diff tests to verify this assumption. This can be done by requesting `${host}/helix-version.txt` (missing == master) and compare this branch to the branch the current PR is running against. 
Like this, we are sure we are comparing the expected branches and this would work for PRs against other branches than `master` (in the above sample, only the urls from the list hosted in a site that uses `breaking-202103` branch would be compared).

**Comment by trieloff** [comment]
There is no branch mismatch. The preflight request will be evaluated for any given branch and if the breaking strain is selected on hlx.page, then it will also be selected on hlx-*.page (unless something is broken in the preflight, but that's the thing the tests should catch.

**Comment by kptdobe** [comment]
ok, I find I get it. What is true on hlx.page is also true on hlx-*.page: the helix-page branch will be used in both cases. But then the diff test is useless because it will compare to DOMs rendered with different branch code not being touched. Those tests should always succeed then. We should then probably ignore those urls.

Still, how do you explain: https://app.circleci.com/pipelines/github/adobe/helix-pages/3856/workflows/8d01467e-ed08-4d98-9a8f-910ec4da4a72/jobs/17763/steps ?

**Comment by kptdobe** [comment]
ok, maybe they should not be ignored because we are testing more than helix-pages.

**Comment by trieloff** [comment]
I'm not sure what's causing the image rewriting to be on/off sometimes, but I think the diff tests may help us figuring it out.

**Comment by kptdobe** [comment]
I just had a flash... In the above circleci failure, `hlx-7` contains the unexpected html. Couldn't it be the cache version of the latest ci round, i.e. the latest breaking-x branch test run which is somehow still delivered ?
When we `hlx publish` to the `hlx-*.page` domain for the CI, we never flush the cache there. Maybe we should!
