### ISSUE TITLE
Remove idx_json.js, idx_json.pipe.js and search providers

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pages#798]
I tihnk those are not used anymore.... can we remove it?

@trieloff  WDYT?

**Comment by trieloff** [comment]
If @dominique-pfister is ok with it, then I'm ok with it.

**Comment by tripodsan** [comment]
also, do we still need to `providers/azure.js` and `providers/algolia.js` ?

**Comment by dominique-pfister** [comment]
> If @dominique-pfister is ok with it, then I'm ok with it.

I'm ok with it. This pipeline step allows requesting `.json` for a file, right? I'm not sure where that might have been used...

**Comment by dominique-pfister** [comment]
> also, do we still need to `providers/azure.js` and `providers/algolia.js` ?

We can remove them, but then we also need to remove `sitemap.js` and its test.

**Comment by tripodsan** [comment]
> I'm ok with it. This pipeline step allows requesting `.json` for a file, right? I'm not sure where that might have been used...

but the index-pipelines parses the HTM, right ?

**Comment by dominique-pfister** [comment]
> > I'm ok with it. This pipeline step allows requesting `.json` for a file, right? I'm not sure where that might have been used...
> 
> but the index-pipelines parses the HTML, right ?

it does, yes, e.g.:

```
Reading HTML from: https://fedpub-adobe.project-helix.page/documentcloud/sign/hub/how-to/what-is-personal-identification-on-bill-of-sale.html
```
