### ISSUE TITLE
SEO: support global metadata from spreadsheet

### ISSUE THREAD

**Issue by rofe** [adobe/helix-pages#800]
From @davidnuescheler's comment in https://github.com/adobe/helix-home/discussions/178#discussioncomment-402937:
> i think it would be great for a range of uses to be able to manage certain meta data in a more table oriented fashion.
> 
> so if had a way to address a page's metadata in a dedicated spreadsheet (json source) that would allow for usecases where a centralized approach to metadata is more intuitive.
> 
> i envision a table that has a column that identifies the path and additionally columns for the meta properties. i think they could be combined with the meta data on the doc with some sort of precendence.
> 
> |  Path  | Keywords | Locale |
> | ----- |----------- | ----------- |
> | /en/home | tag1, tag2 | en-US |
> | /de/home | tag3, tag4 | de-DE |
> 
> i think it would also be great if the Path allows for globbing patterns.

**Comment by rofe** [comment]
Currently blocked by https://github.com/adobe/helix-cli/issues/1689

**Comment by rofe** [comment]
Metadata will be determined as follows:

1. metadata block (author)
2. metadata spreadsheet (admin)
3. content intelligence (helix)

**Comment by rofe** [comment]
That's a lie, right? @trieloff

**Comment by trieloff** [comment]
Yes.
