### ISSUE TITLE
10 words rules for description does not work in Japanese

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pages#844]
Corresponding issue of https://github.com/adobe/theblog/issues/648.

The expected description for page https://theblog--adobe.hlx.page/jp/publish/2021/03/18/cc-design-adobefonts-font-day-2021 is `4月10日「フォントの日」のスペシャル番組。今年はフォントの機能や活⽤のポイントを解説、エンターテインメント的な要素も盛り沢山で、楽しみながらフォントを学んでいただける時間です`. 
The description computation rule (https://github.com/adobe/helix-pages/blob/4071a2c622326d7cbbee2180f5ae84e5bda79f98/src/html.pre.js#L85) is "paragraph with more than 10 words". For this JP string, the regex returns 1.

**Comment by tripodsan** [comment]
I think for japanese, you can use the string length instead.

**Comment by kptdobe** [comment]
I wonder where is this 10-words rule is coming from... We then shorten the text to 25 characters. Why not taking the first paragraph with more than 25 characters in all cases ?!
@rofe might know.

**Comment by kptdobe** [comment]
Now that we have support for the description via the metadata block, I would even get rid of any logic: just take the first non empty `<p>` tag. This is a really confusing rule for authors.

**Comment by rofe** [comment]
> I wonder where is this 10-words rule is coming from... We then shorten the text to 25 characters. Why not taking the first paragraph with more than 25 characters in all cases ?!

@kptdobe You read it wrong 😄: we are taking the first paragraph with 10 or more words, and then shorten to 25 _words_ - not characters.

**Comment by kptdobe** [comment]
Ah right!
